<?php
/**
 * ============================================================================
 * RustDesk Mail Notification Script
 * ============================================================================
 * This script receives the RustDesk ID and sends it by email
 * Requires the rustdesk-mail-config.php configuration file
 * ============================================================================
 */

// Load configuration
$configFile = __DIR__ . '/rustdesk-mail-config.php';

if (!file_exists($configFile)) {
    http_response_code(500);
    die('ERROR: Configuration file not found. Rename rustdesk-mail-config.php.example to rustdesk-mail-config.php and configure it.');
}

require_once($configFile);

// Set timezone
date_default_timezone_set(TIMEZONE);
$date = date('Y-m-d H:i:s');

// ============================================================================
// SECURITY VALIDATION
// ============================================================================

// Check if parameters were sent
if (!isset($_GET["id"]) || !isset($_GET["key"])) {
    http_response_code(400);
    logMessage("ERROR: Missing parameters. Date: $date");
    die('ERROR: Required parameters missing (id and key)');
}

// Validate API key
if ($_GET["key"] !== API_KEY) {
    http_response_code(403);
    logMessage("ERROR: Invalid API key. Date: $date");
    die('ERROR: Invalid API key');
}

// Get and validate ID
$idRust = trim($_GET['id']);

if (empty($idRust)) {
    http_response_code(400);
    logMessage("ERROR: Empty ID. Date: $date");
    die('ERROR: RustDesk ID cannot be empty');
}

// Sanitize ID (only alphanumeric and some special characters)
if (!preg_match('/^[a-zA-Z0-9_-]+$/', $idRust)) {
    http_response_code(400);
    logMessage("ERROR: Invalid ID (characters not allowed). Date: $date");
    die('ERROR: ID contains invalid characters');
}

// ============================================================================
// EMAIL SENDING
// ============================================================================

try {
    // Load PHPMailer
    if (!file_exists(PHPMAILER_PATH) || !file_exists(SMTP_PATH)) {
        throw new Exception('PHPMailer not found. Check paths in rustdesk-mail-config.php');
    }
    
    require(PHPMAILER_PATH);
    require(SMTP_PATH);
    
    $mail = new PHPMailer\PHPMailer\PHPMailer(true);
    
    // SMTP server settings
    $mail->isSMTP();
    $mail->SMTPDebug = SMTP_DEBUG;
    $mail->SMTPAuth = SMTP_AUTH;
    $mail->SMTPSecure = SMTP_SECURE;
    $mail->Host = SMTP_HOST;
    $mail->Port = SMTP_PORT;
    $mail->Username = SMTP_USERNAME;
    $mail->Password = SMTP_PASSWORD;
    
    // Email settings
    $mail->CharSet = 'UTF-8';
    $mail->isHTML(true);
    $mail->setFrom(MAIL_FROM_EMAIL, MAIL_FROM_NAME);
    $mail->addAddress(MAIL_TO_EMAIL);
    
    // Subject and body
    $mail->Subject = "$idRust - " . MAIL_SUBJECT_PREFIX . " - $date";
    
    // HTML body
    $mail->Body = "
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; }
            .container { padding: 20px; background-color: #f5f5f5; }
            .info-box { background-color: white; padding: 15px; border-radius: 5px; margin: 10px 0; }
            .label { font-weight: bold; color: #333; }
            .value { color: #0066cc; font-size: 18px; }
        </style>
    </head>
    <body>
        <div class='container'>
            <h2>New RustDesk Installation</h2>
            <div class='info-box'>
                <p><span class='label'>RustDesk ID:</span> <span class='value'>$idRust</span></p>
                <p><span class='label'>Date/Time:</span> $date</p>
            </div>
            <p style='margin-top: 20px; padding-top: 15px; border-top: 1px solid #ddd; color: #666; font-size: 12px;'>
                <small>This email was automatically generated by the RustDesk installation system.</small><br>
                <small>Created by <a href='https://motta.pro' style='color: #0066cc; text-decoration: none;'>Rodrigo Motta</a> |
                <a href='https://github.com/suportefloripa/RustDesk-Remote-Installer' style='color: #0066cc; text-decoration: none;'>GitHub Project</a></small>
            </p>
        </div>
    </body>
    </html>
    ";
    
    // Alternative text body
    $mail->AltBody = "RustDesk ID: $idRust\nDate/Time: $date";
    
    // Send
    $mail->send();
    
    logMessage("OK: Email sent successfully. ID: $idRust, Date: $date");
    http_response_code(200);
    echo "OK: Email sent successfully. Date: $date";
    
} catch (Exception $e) {
    logMessage("ERROR: Failed to send email. Error: {$mail->ErrorInfo}, Date: $date");
    http_response_code(500);
    echo "ERROR: Failed to send email. Error: {$mail->ErrorInfo}";
}

// ============================================================================
// LOG FUNCTION
// ============================================================================

function logMessage($message) {
    $logFile = __DIR__ . '/rustdesk-mail.log';
    $timestamp = date('Y-m-d H:i:s');
    $logEntry = "[$timestamp] $message\n";
    file_put_contents($logFile, $logEntry, FILE_APPEND);
}

?>

